name: AutoPost Bot

on:
  # Запуск по расписанию (каждые 2 часа)
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "TG_API_ID=${{ secrets.TG_API_ID }}" >> .env
          echo "TG_API_HASH=${{ secrets.TG_API_HASH }}" >> .env
          echo "TG_CHANNEL_USERNAME=${{ secrets.TG_CHANNEL_USERNAME }}" >> .env
          echo "TG_LOG_CHANNEL_ID=${{ secrets.TG_LOG_CHANNEL_ID }}" >> .env
          echo "VK_TOKEN=${{ secrets.VK_TOKEN }}" >> .env
          echo "VK_GROUP_ID=${{ secrets.VK_GROUP_ID }}" >> .env
          echo "START_FROM_ID=${{ secrets.START_FROM_ID }}" >> .env

      - name: Restore Session File
        run: |
          echo "${{ secrets.TG_SESSION_B64 }}" | base64 -d > anon_session.session

      - name: Run Script
        run: python main.py
